##### Copyright 2019 The TensorFlow Authors. Edited by Eric Braude

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Assignment 2 Part 1 - Alessandro Allegranzi


# TensorFlow 2 quickstart for beginners, edited by Eric Braude

I recommend runniing on Colab.
<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/quickstart/beginner"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This uses [Keras](https://www.tensorflow.org/guide/keras/overview) to:

1. Build a neural network that classifies images.
2. Train this neural network.
3. And, finally, evaluate the accuracy of the model.


This is a [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) notebook file. Python programs are run directly in the browser—a great way to learn and use TensorFlow. To follow this tutorial, run the notebook in Google Colab by clicking the button at the top of this page.

1. In Colab, connect to a Python runtime: At the top-right of the menu bar, select *CONNECT*. (I did not need to do this- EB)
2. To run all the notebook code cells (i.e., not just one at a time): Select *Runtime* > *Run all*.

AS NEEDED ... Download and install TensorFlow 2. Import TensorFlow into your program:

Note: Upgrade `pip` to install the TensorFlow 2 package. See the [install guide](https://www.tensorflow.org/install) for details.

In [1]:
import tensorflow as tf

Load and prepare the [MNIST dataset](http://yann.lecun.com/exdb/mnist/). Visualize: https://www.tensorflow.org/datasets/catalog/mnist Convert the samples from integers to floating-point numbers:

In [73]:
# INTENT: Load the IMDB review data.

mnist = tf.keras.datasets.mnist # one of a handful of data sets known to Keras/TensorFlow
# mnist.load_data() produces a pair of input/output tensors for training
# and one for testing.
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print("===========y_train===========")
print(tf.shape(y_train))
print(y_train)
x_train, x_test = x_train / 255.0, x_test / 255.0 # scale down input
print("===========x_train===========")
print(tf.shape(x_train))
print("===========x_train element 0 (28 rows of 28 gray values)===========")
print(x_train[0])

===========y_train===========
tf.Tensor([60000], shape=(1,), dtype=int32)
[5 0 4 ... 5 6 8]
===========x_train===========
tf.Tensor([60000    28    28], shape=(3,), dtype=int32)
===========x_train element 0 (28 rows of 28 gray values)===========
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.


Build the `tf.keras.Sequential` model (object) by stacking layers.

https://www.tensorflow.org/api_docs/python/tf/keras/Sequential

In [74]:
model = tf.keras.models.Sequential([ # layer format for the neural net
  tf.keras.layers.Flatten(input_shape=(28, 28)), # each pixel (grayscale value) mapped to one of 784 nodes
  # tf.keras.layers.Dense(25, activation='sigmoid'), # fully connected to hidden layer with sigmoid, lowered neurons to 25
  tf.keras.layers.Dense(150, activation='relu'), # Increased neurons up to 150 and used relu to improve model.
  # Dropout layer randomly sets its input units to 0 at 20% rate at each training step
  # The other inputs are scaled up by 1/0.8 so sum over all inputs is unchanged
  # Illustrative figure: http://laid.delanover.com/wp-content/uploads/2018/02/dropout.png
  # (see https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout)
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10) # e.g., output #7 expresses degree to which the input is a 7
])


For each example the model returns a vector of "[logits](https://developers.google.com/machine-learning/glossary#logits)" or "[log-odds](https://developers.google.com/machine-learning/glossary#log-odds)" scores, one for each class.

In other words, a tensor where the highest value indicates the most likely output.

https://en.wikipedia.org/wiki/Logit

model() acts like a function, returning the neural net object.

In [75]:
print("===========first element of x_train (29 rows)===========")
print(x_train[:1])

predictions = model(x_train[:1]).numpy() # numpy() converts the tensor output
print("===========untrained output of first training set input===========")
predictions

===========first element of x_train (29 rows)===========
[[[0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0. 

array([[-0.09860671, -0.32874662,  0.4740216 , -0.24705184,  0.22679141,
         0.07655796, -0.20971206,  0.08804052, -0.2761206 , -0.26757535]],
      dtype=float32)

The `tf.nn.softmax` function converts these logits to "probabilities" for each class (summing to 1).

In [76]:
tf.nn.softmax(predictions).numpy()

array([[0.09270121, 0.07364392, 0.1643519 , 0.07991283, 0.1283524 ,
        0.11044814, 0.08295316, 0.11172369, 0.07762329, 0.07828946]],
      dtype=float32)

Note: It is possible to bake this `tf.nn.softmax` in as the activation function for the last layer of the network. While this can make the model output more directly interpretable, this approach is discouraged as it's impossible to
provide an exact and numerically stable loss calculation for all models when using a softmax output.

The `losses.SparseCategoricalCrossentropy` loss takes a vector of logits and a `True` index and returns a scalar loss for each example.

sparse categorical crossentropy
(https://docs.google.com/document/d/16v7AIXuwAwdOZxorwSDXKRGzJA8jUYAR_D-QJTxEiyA/edit?usp=sharing)
We give it a short name.

In [77]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the true class:
It is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to `-tf.math.log(1/10) ~= 2.3`.

Recall that y_train is the target (desired output) tensor. We select the first element.

In [78]:
loss_fn(y_train[:1], predictions).numpy()

2.2032092

In [79]:
# Put together the NN with training process, loss, and means of evaluation.
# 'accuracy' = proportion of correct predictions vs. total number of cases
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

The `Model.fit` method adjusts the model's parameters to minimize the loss:

In [80]:
# # Calculate half the number of samples.
# num_samples = int(0.5 * len(x_train))

# # Select a subset of half the original data
# x_train_subset = x_train[:num_samples]
# y_train_subset = y_train[:num_samples]

# Train it with 8 epochs and full data
model.fit(x_train, y_train, epochs=8)

Epoch 1/8
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2805 - accuracy: 0.9194
Epoch 2/8
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1326 - accuracy: 0.9606
Epoch 3/8
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0980 - accuracy: 0.9702
Epoch 4/8
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0800 - accuracy: 0.9746
Epoch 5/8
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0676 - accuracy: 0.9790
Epoch 6/8
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0593 - accuracy: 0.9810
Epoch 7/8
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0527 - accuracy: 0.9834
Epoch 8/8
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0447 - accuracy: 0.9856


The `Model.evaluate` method checks the models performance, usually on a "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)" or "[Test-set](https://developers.google.com/machine-learning/glossary#test-set)".

In [81]:
# Accuracy = fraction of correct test pairs
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0676 - accuracy: 0.9803 - 803ms/epoch - 3ms/step


[0.06763662397861481, 0.9803000092506409]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [82]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [83]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.69346784e-10, 8.12970871e-12, 5.15578620e-07, 2.08178449e-06,
        2.42672167e-11, 1.31815519e-08, 1.05826252e-16, 9.99995947e-01,
        4.25251917e-11, 1.59513081e-06],
       [6.53053278e-10, 8.27759959e-06, 9.99990582e-01, 1.03168338e-06,
        8.59171823e-19, 2.12026894e-08, 2.38588385e-08, 6.55862474e-12,
        8.24071336e-08, 6.91888857e-16],
       [2.90136626e-08, 9.99329090e-01, 1.91368072e-05, 9.31339230e-07,
        2.65980407e-06, 4.85643966e-07, 6.52986182e-06, 6.16225065e-04,
        2.48050983e-05, 9.69984555e-08],
       [9.99868751e-01, 2.38761060e-11, 2.16848633e-07, 4.92103247e-10,
        6.76955665e-08, 6.91781068e-08, 1.24643280e-04, 5.71941291e-06,
        7.70536523e-10, 4.00168119e-07],
       [5.44614220e-09, 2.61326599e-10, 1.82564435e-07, 3.79575760e-10,
        9.98593509e-01, 6.15089935e-09, 1.05871194e-07, 5.17831495e-06,
        2.88057089e-09, 1.40100555e-03]], dtype=float32)>